mifinca/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mifinca.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

mifinca/Controllers/bodegasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using mifinca.Models;

namespace mifinca.Controllers
{
    public class bodegasController : Controller
    {
        private mifincaEntities db = new mifincaEntities();

        // GET: bodegas
        public ActionResult Index()
        {
            return View(db.bodega.ToList());
        }

        // GET: bodegas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bodega bodega = db.bodega.Find(id);
            if (bodega == null)
            {
                return HttpNotFound();
            }
            return View(bodega);
        }

        // GET: bodegas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: bodegas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_bodega,id_finca,fecha_ingreso_producto")] bodega bodega)
        {
            if (ModelState.IsValid)
            {
                db.bodega.Add(bodega);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bodega);
        }

        // GET: bodegas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bodega bodega = db.bodega.Find(id);
            if (bodega == null)
            {
                return HttpNotFound();
            }
            return View(bodega);
        }

        // POST: bodegas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_bodega,id_finca,fecha_ingreso_producto")] bodega bodega)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bodega).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bodega);
        }

        // GET: bodegas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bodega bodega = db.bodega.Find(id);
            if (bodega == null)
            {
                return HttpNotFound();
            }
            return View(bodega);
        }

        // POST: bodegas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            bodega bodega = db.bodega.Find(id);
            db.bodega.Remove(bodega);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

mifinca/Controllers/finanzasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mifinca.Controllers
{
    public class finanzasController : Controller
    {
        // GET: finanzas
        public ActionResult Index()
        {
            return View();
        }
    }
}

mifinca/Controllers/fincasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using mifinca.Models;

namespace mifinca.Controllers
{
    public class fincasController : Controller
    {
        private mifincaEntities db = new mifincaEntities();

        // GET: fincas
        public ActionResult Index()
        {
            var finca = db.finca.Include(f => f.bodega);
            return View(finca.ToList());
        }

        // GET: fincas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            finca finca = db.finca.Find(id);
            if (finca == null)
            {
                return HttpNotFound();
            }
            return View(finca);
        }

        // GET: fincas/Create
        public ActionResult Create()
        {
            ViewBag.id_bodega = new SelectList(db.bodega, "id_bodega", "id_bodega");
            return View();
        }

        // POST: fincas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_finca,id_bodega,foto_finca,nombre_finca,extension,planoCatastral,localizacionEntrada,tablones,desripcion,msnm_altura")] finca finca)
        {
            if (ModelState.IsValid)
            {
                db.finca.Add(finca);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_bodega = new SelectList(db.bodega, "id_bodega", "id_bodega", finca.id_bodega);
            return View(finca);
        }

        // GET: fincas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            finca finca = db.finca.Find(id);
            if (finca == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_bodega = new SelectList(db.bodega, "id_bodega", "id_bodega", finca.id_bodega);
            return View(finca);
        }

        // POST: fincas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HttpPostedFileBase update_foto_finca, HttpPostedFileBase update_planoCatastral , [Bind(Include = "id_finca,id_bodega,foto_finca,nombre_finca,extension,planoCatastral,localizacionEntrada,tablones,desripcion,msnm_altura")] finca finca )
        {
            if (ModelState.IsValid)
            {

                if (update_planoCatastral != null)
                {
                    string _FileNamePlanoCatastral = Path.GetFileName(update_planoCatastral.FileName);
                    string _path = Path.Combine(Server.MapPath("~/imgs/plano_catastral"), _FileNamePlanoCatastral);
                    update_planoCatastral.SaveAs(_path);

                    finca.planoCatastral = _FileNamePlanoCatastral;
                    db.Entry(finca).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                if (update_foto_finca != null)
                {
                    string _FileName = Path.GetFileName(update_foto_finca.FileName);
                    string _path = Path.Combine(Server.MapPath("~/imgs/fincas"), _FileName);
                    update_foto_finca.SaveAs(_path);

                    finca.foto_finca = _FileName;
                    db.Entry(finca).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                

                //valida si no carga  foto_finca
                if (finca.foto_finca == null || finca.planoCatastral == null)
                {
                    return RedirectToAction("Index");
                }


                db.Entry(finca).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_bodega = new SelectList(db.bodega, "id_bodega", "id_bodega", finca.id_bodega);
            return View(finca);
        }

       

        // GET: fincas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            finca finca = db.finca.Find(id);
            if (finca == null)
            {
                return HttpNotFound();
            }
            return View(finca);
        }

        // POST: fincas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            finca finca = db.finca.Find(id);
            db.finca.Remove(finca);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

mifinca/Controllers/tareasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using mifinca.Models;

namespace mifinca.Controllers
{
    public class tareasController : Controller
    {
        private mifincaEntities db = new mifincaEntities();

        // GET: tareas
        public ActionResult Index()
        {
            var tarea = db.tarea.Include(t => t.empleado).Include(t => t.tipo_tarea);
            return View(tarea.ToList());
        }

        // GET: tareas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tarea tarea = db.tarea.Find(id);
            if (tarea == null)
            {
                return HttpNotFound();
            }
            return View(tarea);
        }

        // GET: tareas/Create
        public ActionResult Create()
        {
            ViewBag.id_empleado = new SelectList(db.empleado, "id_empleado", "nombre_empleado");
            ViewBag.id_tipo = new SelectList(db.tipo_tarea, "id_tipo", "tipo");
            return View();
        }

        // POST: tareas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_tarea,id_empleado,id_tipo,fecha_inicio,fecha_fin,descripcion")] tarea tarea)
        {
            if (ModelState.IsValid)
            {
                db.tarea.Add(tarea);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_empleado = new SelectList(db.empleado, "id_empleado", "nombre_empleado", tarea.id_empleado);
            ViewBag.id_tipo = new SelectList(db.tipo_tarea, "id_tipo", "tipo", tarea.id_tipo);
            return View(tarea);
        }

        // GET: tareas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tarea tarea = db.tarea.Find(id);
            if (tarea == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_empleado = new SelectList(db.empleado, "id_empleado", "nombre_empleado", tarea.id_empleado);
            ViewBag.id_tipo = new SelectList(db.tipo_tarea, "id_tipo", "tipo", tarea.id_tipo);
            return View(tarea);
        }

        // POST: tareas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_tarea,id_empleado,id_tipo,fecha_inicio,fecha_fin,descripcion")] tarea tarea)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tarea).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_empleado = new SelectList(db.empleado, "id_empleado", "nombre_empleado", tarea.id_empleado);
            ViewBag.id_tipo = new SelectList(db.tipo_tarea, "id_tipo", "tipo", tarea.id_tipo);
            return View(tarea);
        }

        // GET: tareas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tarea tarea = db.tarea.Find(id);
            if (tarea == null)
            {
                return HttpNotFound();
            }
            return View(tarea);
        }

        // POST: tareas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tarea tarea = db.tarea.Find(id);
            db.tarea.Remove(tarea);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

mifinca/Views/Home/About.cshtml
@{
    ViewBag.Title = "Finanzas";
}
<h2>@ViewBag.Title.</h2>

<p>Todo lo relacionado con finanzas</p>

mifinca/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

mifinca/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@*<h2>@Html.ActionLink("Bodega", "Index", "bodegas")</h2>*@

<style>
    .card:hover {
        transform: scale(1.05);
        box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
    }

    

    .size_lottie{
        width: 300px;
        height: 300px;
    }
</style>


<div class="container">
    <!-- fila -->
    <div class="row">

        <div class="col-12 col-md-6 col-lg-4">
            <!-- card -->
            <div class="card text-center border border-primary shadow-0 m-2">
                <div class="card-body">
                    <h5 class="card-title">@Html.ActionLink("Finca", "Index", "fincas", new { area = "" }, new { @class = "stretched-link" })</h5>

                    <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                        @*<img src="~/imgs/propiedades.jpg" class="img-fluid" />*@
                        <lottie-player class="rounded mx-auto d-block size_lottie img-fluid" src="https://assets5.lottiefiles.com/packages/lf20_svy4ivvy.json" mode="bounce" background="transparent" speed="1" hover loop autoplay></lottie-player>
                        <a href="#!">
                            <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
                        </a>
                    </div>
                </div>

            </div>
            <!-- fin card -->
        </div>

        <div class="col-12 col-md-6 col-lg-4">
            <!-- card -->
            <div class="card text-center border border-primary shadow-0 m-2 ">
                <div class="card-body">
                    <h5 class="card-title">@Html.ActionLink("Planilla", "Index", "planillas", new { area = "" }, new { @class = "stretched-link" })</h5>

                    <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                        @*<img src="~/imgs/planilla.png" class="img-fluid" />*@
                        <lottie-player class="rounded mx-auto d-block size_lottie img-fluid" src="https://assets1.lottiefiles.com/private_files/lf30_Jk3ls8.json" mode="bounce" background="transparent" speed="0.8" hover loop autoplay></lottie-player>
                        <a href="#!">
                            <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
                        </a>
                    </div>
                </div>

            </div>
            <!-- fin card -->
        </div>

        <div class="col-12 col-md-6 col-lg-4">
            <!-- card -->
            <div class="card text-center border border-primary shadow-0 m-2">
                <div class="card-body">
                    <h5 class="card-title">@Html.ActionLink("Finanzas", "Index", "finanzas", new { area = "" }, new { @class = "stretched-link" })</h5>
                </div>
                <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                    @*<img src="~/imgs/finanzas.jpg" class="img-fluid" />*@
                    <lottie-player class="rounded mx-auto d-block size_lottie img-fluid" src="https://assets5.lottiefiles.com/packages/lf20_l5o1uey5.json" mode="bounce" background="transparent" speed="1" hover loop autoplay></lottie-player>
                    <a href="#!">
                        <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
                    </a>
                </div>
            </div>
            <!-- fin card -->
        </div>





        <div class="col-12 col-md-6 col-lg-4">
            <!-- card -->
            <div class="card text-center border border-primary shadow-0 m-2 ">
                <div class="card-body">
                    <h5 class="card-title">@Html.ActionLink("Empleados", "Index", "empleadoes", new { area = "" }, new { @class = "stretched-link" })</h5>

                    <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                        @*<img src="~/imgs/empleados.jpg" class="img-fluid" />*@
                        <lottie-player class="rounded mx-auto d-block size_lottie img-fluid" src="https://assets4.lottiefiles.com/packages/lf20_khtt8ejx.json" mode="bounce" background="transparent" speed="1" hover loop autoplay></lottie-player>
                        <a href="#!">
                            <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
                        </a>
                    </div>
                </div>

            </div>
            <!-- fin card -->
        </div>

        <div class="col-12 col-md-6 col-lg-4">
            <!-- card -->
            <div class="card text-center border border-primary shadow-0 m-2">
                <div class="card-body">
                    <h5 class="card-title">@Html.ActionLink("Tareas", "Index", "tareas", new { area = "" }, new { @class = "stretched-link" })</h5>

                    <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                        @*<img src="~/imgs/tarea.png" class="img-fluid" />*@
                        <lottie-player class="rounded mx-auto d-block size_lottie img-fluid" src="https://assets4.lottiefiles.com/private_files/lf30_fvqxryww.json" background="transparent" speed="1" hover loop autoplay></lottie-player>
                        <a href="#!">
                            <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
                        </a>
                    </div>
                </div>

            </div>
            <!-- fin card -->
        </div>

        <div class="col-12 col-md-6 col-lg-4">
            <!-- card -->
            <div class="card text-center border border-primary shadow-0 m-2">
                <div class="card-body">
                    <h5 class="card-title">@Html.ActionLink("Bodega", "Index", "productoes", new { area = "" }, new { @class = "stretched-link" })</h5>

                    <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                        @*<img src="~/imgs/bodega.png" class="img-fluid" />*@
                        <lottie-player class="rounded mx-auto d-block size_lottie img-fluid" src="https://assets4.lottiefiles.com/packages/lf20_ribepxhx.json" mode="bounce" background="transparent" speed="1" hover loop autoplay></lottie-player>
                        <a href="#!">
                            <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
                        </a>
                    </div>
                </div>

            </div>
            <!-- fin card -->
        </div>
    </div>
    <!-- fin fila -->

</div>

<script src="https://unpkg.com/@("@")lottiefiles/lottie-player@("@")latest/dist/lottie-player.js"></script>