mifinca/Models/planilla.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mifinca.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class planilla
    {
        public int id_planilla { get; set; }
        public int id_empleado { get; set; }
        public int id_finca { get; set; }
        public System.DateTime fecha_resolucion { get; set; }
        public string csv_planilla { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual finca finca { get; set; }
        public HttpPostedFileBase update_csv_planilla { get; set; }

        public HttpPostedFileBase insert_csv_planilla { get; set; }
    }

  


}

mifinca/Controllers/planillasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using mifinca.Models;

namespace mifinca.Controllers
{
    public class planillasController : Controller
    {
        private mifincaEntities db = new mifincaEntities();

        // GET: planillas

        

        public ActionResult Index()
        {
            var planilla = db.planilla.Include(p => p.empleado).Include(p => p.finca);
            return View(planilla.ToList());
        }

        // GET: planillas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            planilla planilla = db.planilla.Find(id);
            if (planilla == null)
            {
                return HttpNotFound();
            }
            return View(planilla);
        }

        // GET: planillas/Create
        public ActionResult Create()
        {
            ViewBag.id_empleado = new SelectList(db.empleado, "id_empleado", "nombre_empleado");
            //ViewBag.id_finca = new SelectList(db.finca, "id_finca", "foto_finca");
            ViewBag.id_finca = new SelectList(db.finca, "id_finca", "nombre_finca");
            return View();
        }

        // POST: planillas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase  insert_csv_planilla , [Bind(Include = "id_planilla,id_empleado,id_finca,fecha_resolucion,csv_planilla")] planilla planilla )
        {
            if (ModelState.IsValid)
            {
                if (insert_csv_planilla != null)
                {
                    string _FileNameInsertPlanilla = Path.GetFileName(insert_csv_planilla.FileName + ".gsheet");
                    string _path = Path.Combine(Server.MapPath("~/planilla"), _FileNameInsertPlanilla);
                    insert_csv_planilla.SaveAs(_path);

                    planilla.csv_planilla = _FileNameInsertPlanilla;
                    db.planilla.Add(planilla);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                
                db.planilla.Add(planilla);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_empleado = new SelectList(db.empleado, "id_empleado", "nombre_empleado", planilla.id_empleado);
            //ViewBag.id_finca = new SelectList(db.finca, "id_finca", "foto_finca", planilla.id_finca);
            ViewBag.id_finca = new SelectList(db.finca, "id_finca", "nombre_finca", planilla.id_finca);
            return View(planilla);
        }

        // GET: planillas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            planilla planilla = db.planilla.Find(id);
            if (planilla == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_empleado = new SelectList(db.empleado, "id_empleado", "nombre_empleado", planilla.id_empleado);
            //ViewBag.id_finca = new SelectList(db.finca, "id_finca", "foto_finca", planilla.id_finca);
            ViewBag.id_finca = new SelectList(db.finca, "id_finca", "nombre_finca", planilla.id_finca);
            return View(planilla);
        }

        // POST: planillas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HttpPostedFileBase update_csv_planilla, [Bind(Include = "id_planilla,id_empleado,id_finca,fecha_resolucion,csv_planilla")] planilla planilla)
        {
            if (ModelState.IsValid)
            {

                if (update_csv_planilla != null)
                {
                    string _FileNameUpdatePlanilla = Path.GetFileName(update_csv_planilla.FileName + ".gsheet");
                    string _path = Path.Combine(Server.MapPath("~/planilla"), _FileNameUpdatePlanilla);
                    update_csv_planilla.SaveAs(_path);

                    planilla.csv_planilla = _FileNameUpdatePlanilla;
                    db.Entry(planilla).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }



                db.Entry(planilla).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_empleado = new SelectList(db.empleado, "id_empleado", "nombre_empleado", planilla.id_empleado);
            ViewBag.id_finca = new SelectList(db.finca, "id_finca", "foto_finca", planilla.id_finca);
            return View(planilla);

            //return RedirectToAction("Index");
        }

        // GET: planillas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            planilla planilla = db.planilla.Find(id);
            if (planilla == null)
            {
                return HttpNotFound();
            }
            return View(planilla);
        }

        // POST: planillas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            planilla planilla = db.planilla.Find(id);
            db.planilla.Remove(planilla);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

mifinca/Views/planillas/Create.cshtml
@model mifinca.Models.planilla

@{
    ViewBag.Title = "Create";
}

<h2>Crear planilla</h2>

<style>
    .none {
        display: none;
    }
</style>

@*@using (Html.BeginForm())*@
@using (Html.BeginForm("Create", "planillas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group mb-3 d-none">
        @Html.LabelFor(model => model.id_empleado, "Nombre del empleado", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("id_empleado", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.id_empleado, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group mb-3">
        @Html.LabelFor(model => model.id_finca, "Nombre de la finca", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @* lo muestro pero no se envia *@
            @Html.DropDownList("id_finca", null, htmlAttributes: new { @class = "form-control", @disabled = "disabled" })
            @* no se muestra pero si se envia *@
            @Html.DropDownList("id_finca", null, htmlAttributes: new { @class = "form-control none" })
            @Html.ValidationMessageFor(model => model.id_finca, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group mb-3">
        @Html.LabelFor(model => model.fecha_resolucion, "Fecha de resolución", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.fecha_resolucion, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
            @Html.ValidationMessageFor(model => model.fecha_resolucion, "", new { @class = "text-danger" })
        </div>
        <script>
            const elem = document.querySelector('input[name="fecha_resolucion"]');
            const datepicker = new Datepicker(elem, {
                format: "yyyy/mm/dd"
            });
        </script>
    </div>

    <div class="form-group mb-3">
        @Html.LabelFor(model => model.csv_planilla, "CSV de la planilla", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBox("insert_csv_planilla", "", new { type = "file", accept = ".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel", @class = "form-control" }) <br />

            @*@Html.EditorFor(model => model.csv_planilla, new { htmlAttributes = new { @class = "form-control d-none" } })*@
            @*@Html.ValidationMessageFor(model => model.csv_planilla, "", new { @class = "text-danger" })*@
        </div>
    </div>

    @*<div class="form-group mb-3">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>*@
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Crear" class="btn btn-success btn-lg input-block-level form-control mb-2" />
            @Html.ActionLink("Salir sin crear", "Index", new { area = "" }, new { @class = "btn btn-danger btn-lg d-flex justify-content-center" })
        </div>
    </div>
</div>
}

@*<div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

mifinca/Views/planillas/Delete.cshtml
@model mifinca.Models.planilla

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar planilla</h2>

<h3>¿Esta seguro eliminar la planilla?</h3>
<div>
    <p class="text-danger">La siguiente acción no se puede deshacer </p>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @*@Html.DisplayNameFor(model => model.fecha_resolucion)*@Fecha Resolucion
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.fecha_resolucion)*@
            
            @Model.fecha_resolucion.ToString("yyyy/MM/dd")
            @*@DateTime.Parse(Html.DisplayFor(model => model.fecha_resolucion).ToString()).ToShortDateString()*@

        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.csv_planilla)*@Archivo de la planilla
        </dt>

        <dd>
            @Html.DisplayFor(model => model.csv_planilla)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.empleado.nombre_empleado) Nombre de Empleado
        </dt>

        <dd>
            @Html.DisplayFor(model => model.empleado.nombre_empleado)
        </dd>*@

        <dt>
            @*@Html.DisplayNameFor(model => model.finca.nombre_finca)*@ Nombre de finca
        </dt>

        <dd>
            @Html.DisplayFor(model => model.finca.nombre_finca)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        @*<div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>*@
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Eliminar" class="btn btn-danger btn-lg input-block-level form-control mb-2" />
                @Html.ActionLink("Salir sin eliminar", "Index", new { area = "" }, new { @class = "btn btn-success btn-lg d-flex justify-content-center" })
            </div>
        </div>
    }
</div>

mifinca/Views/planillas/Details.cshtml
@model mifinca.Models.planilla

@{
    ViewBag.Title = "Details";
}

<h2>Detalle de la planilla</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @*Html.DisplayNameFor(model => model.fecha_resolucion)*@Fecha Resolucion
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.fecha_resolucion)*@
            @Model.fecha_resolucion.ToString("yyyy/MM/dd")
            @*@DateTime.Parse(Html.DisplayFor(model => model.fecha_resolucion).ToString()).ToShortDateString()*@
        </dd>

        @*<dt>
                Html.DisplayNameFor(model => model.empleado.nombre_empleado)Nombre de Empleado
            </dt>

            <dd>
                @Html.DisplayFor(model => model.empleado.nombre_empleado)
            </dd>*@

        @*<dt>
                Html.DisplayNameFor(model => model.finca.foto_finca)Foto Finca
            </dt>

            <dd>
                @Html.DisplayFor(model => model.finca.foto_finca)
            </dd>*@

        <dt>
            @*Html.DisplayNameFor(model => model.csv_planilla)*@Archivo de la planilla
        </dt>

        <dd>
            @Html.DisplayFor(model => model.csv_planilla)

        </dd>

    </dl>

    @*<iframe src="https://view.officeapps.live.com/op/embed.aspx?src=https://github.com/DouglasLino/proyectoCambioClimatico/raw/master/public/tables/rio_paz.xlsx" width='100%' height='565px' frameborder='0'> </iframe>*@

<div class="responsive">
    <iframe width="1520" height="730" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vTELAT74xn-fdoEgKDSPcL35aBV3Dg-LhtTaUKYI6XUN7F7SLqtMdAjB2inFxr98_xY524Olbws7Jyo/pubhtml?widget=true&amp;headers=false"></iframe>
</div>
    
    @*<div id="myExcelDiv" style="width: 100%; height: 100%"></div>*@
    @*<script type="text/javascript" src="https://onedrive.live.com/embed?resid=B86CE9E6B7062E13%21110&authkey=%21AG5FtGqXpSy-ivo&em=3&wdDivId=%22myExcelDiv%22&wdDownloadButton=1&wdAllowInteractivity=0"></script>*@

</div>
<p>
    <div class="col-md-offset-2 col-md-10">
        @Html.ActionLink("Editar", "Edit", new { id = Model.id_planilla }, new { @class = "btn btn-success btn-lg input-block-level form-control mb-2" })
        @Html.ActionLink("Salir", "Index", new { area = "" }, new { @class = "btn btn-danger btn-lg d-flex justify-content-center" })
    </div>
   
    @*@Html.ActionLink("Back to List", "Index")*@
</p>

mifinca/Views/planillas/Edit.cshtml
@model mifinca.Models.planilla

@{
    ViewBag.Title = "Edit";
}

<!-- Bootstrap DatePicker -->
<script type="text/javascript" src='https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.3.min.js'></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css" type="text/css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.js" type="text/javascript"></script>
<!-- Bootstrap DatePicker -->
<style>
    .none {
        display: none;
    }
</style>


<h2>Editar plantilla</h2>


@*@using (Html.BeginForm())*@
@using (Html.BeginForm("Edit", "planillas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_planilla)

        @* se oculta pero se envia *@
        <div class="form-group mb-2 d-none">
            @Html.LabelFor(model => model.id_empleado, "Nombre del Empleado", htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                @Html.DropDownList("id_empleado", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_empleado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mb-3">
            @Html.LabelFor(model => model.id_finca, "Nombre de la Finca", htmlAttributes: new { @class = "control-label" })
            <div class="col-md-10">
                @* lo muestro pero no se envia *@
                @Html.DropDownList("id_finca", null, htmlAttributes: new { @class = "form-control", @disabled = "disabled" })
                @* no se muestra pero si se envia *@
                @Html.DropDownList("id_finca", null, htmlAttributes: new { @class = "form-control none" })
                @Html.ValidationMessageFor(model => model.id_finca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mb-3">
            @Html.LabelFor(model => model.fecha_resolucion, "Fecha de Resolucion", htmlAttributes: new { @class = "control-label " })
            <div class="col-md-10">

                @Html.EditorFor(model => model.fecha_resolucion,
                                new{ htmlAttributes = new { @class = "form-control",
                                    @Value = Model.fecha_resolucion.Date.ToString("yyyy/MM/dd")}})
                @Html.ValidationMessageFor(model => model.fecha_resolucion, "", new { @class = "text-danger" })

                <script>
                    const elem = document.querySelector('input[name="fecha_resolucion"]');
                    const datepicker = new Datepicker(elem, {
                        format: "yyyy/mm/dd"
                    });
                </script>
            </div>
        </div>


        <div class="form-group mb-3">
            @Html.LabelFor(model => model.csv_planilla, "Archivo de Planilla", htmlAttributes: new { @class = "control-label " })
            <div class="col-md-10">
                @Html.TextBox("update_csv_planilla", "", new { type = "file", accept = ".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel", @class = "form-control" }) <br />

                @* Oculto este campo pero se envia *@
                @Html.EditorFor(model => model.csv_planilla, new { htmlAttributes = new { @class = "form-control d-none" } })
                @Html.ValidationMessageFor(model => model.csv_planilla, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mb-3">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success btn-lg input-block-level form-control mb-2" />
                @Html.ActionLink("Salir sin guardar", "Index", new { area = "" }, new { @class = "btn btn-danger btn-lg d-flex justify-content-center" })
            </div>
        </div>


    </div>
}




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


}

mifinca/Views/planillas/Index.cshtml
@model IEnumerable<mifinca.Models.planilla>

@{
    ViewBag.Title = "Index";
}

<style>
    button a {
        color: white;
        text-decoration: none;
    }

        button a:hover {
            color: white;
        }
</style>


<section class="container">
    <div class=" row align-items-center mb-3">
        <h1 class="text-center">Planilla</h1><!--H1 con el titulo-->

        <div class="col-10 p-0">
            <!--Se definen Breakpoints-->
            <div  id ="buscador" class="input-group" >
                <!--Buscador-->
                <span class="input-group-text" id="basic-addon1">Empleado:</span>
                <input type="text" class="form-control" placeholder="Jorge Daniel" aria-label="Username" aria-describedby="basic-addon1">
            </div>
        </div>
        <div class="col-2">
            <!--Botton de agregar nuevo empleado-->
            <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#NewEmpleado">@Html.ActionLink("Agregar planilla", "Create")</button>
        </div>
    </div>

</section>


<div class="table-responsive">
    <table class="table table-striped">
        <tr class="table-dark">
            @*<th>
                @Html.DisplayNameFor(model => model.empleado.nombre_empleado)
                Nombre del empleado
            </th>*@
            <th>
                @*@Html.DisplayNameFor(model => model.fecha_resolucion)*@
                Fech de resolución
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.csv_planilla)*@
                Archivo de planilla
            </th>

            <th>
                @*@Html.DisplayNameFor(model => model.finca.foto_finca)*@
                Nombre de finca
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                @*<td>
                    @Html.DisplayFor(modelItem => item.empleado.nombre_empleado)
                </td>*@
                <td>
                    @*@Html.DisplayFor(modelItem => item.fecha_resolucion)*@
                    @Convert.ToDateTime(item.fecha_resolucion).ToString("yyyy/MM/dd")

                    @* formato anterior *@
                    @*@DateTime.Parse(Html.DisplayFor(modelItem => item.fecha_resolucion).ToString()).ToLongDateString();*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.csv_planilla)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.finca.nombre_finca)
                </td>
                <td>
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <button type="button" class="btn btn-secondary">@Html.ActionLink("Editar", "Edit", new { id = item.id_planilla })</button>
                        <button type="button" class="btn btn-secondary">@Html.ActionLink("Detalle", "Details", new { id = item.id_planilla })</button>
                        <button type="button" class="btn btn-danger">@Html.ActionLink("Eliminar", "Delete", new { id = item.id_planilla })</button>
                    </div>
                </td>
            </tr>
        }

    </table>

</div>